@hostname = http://localhost
@port = 3000
@baseUrl = {{hostname}}:{{port}}
@contentType = application/json
@authToken = {{authenticate.response.body.accessToken}}

# @name create_account
# @prompt unique Unique identification for user
POST {{baseUrl}}/accounts
Content-Type: {{contentType}}

{
  "name": "John Doe",
  "email": "john.doe_{{unique}}@example.com",
  "password": "12345678"
}

###

# @name authenticate
# @prompt unique Unique identification for user
POST {{baseUrl}}/sessions
Content-Type: {{contentType}}

{
  "email": "john.doe_{{unique}}@example.com",
  "password": "12345678"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 1",
  "content": "Conteúdo da pergunta"
}
