version: "3.8"

services:
  postgres:
    container_name: nest-clean-pg
    env_file:
      - .env
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres
